DECLARE @CLIENTE VARCHAR(10);
DECLARE @IDADE INT;
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @CUSTO FLOAT;


SET @CLIENTE = 'João';
SET @IDADE = 10;
SET @DATA_NASCIMENTO = '10-01-2007';
SET @CUSTO = 10.23;