DECLARE @CODIGO VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @I INT;
SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;
WHILE @I <= @NUMERO_PRODUTOS
BEGIN
        SELECT @CODIGO = X.[CODIGO DO PRODUTO], @NOME = X.[NOME DO PRODUTO]
        FROM ( SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, * FROM [TABELA DE PRODUTOS]) X
        WHERE X.RowNum = @I;
        PRINT @CODIGO + ' - ' + @NOME;
        SET @I = @I + 1;
END;