DECLARE @DATAINICIAL DATE;
DECLARE @DATAFINAL DATE;
DECLARE @NUMNOTAS INT;
SET @DATAINICIAL = '20170101';
SET @DATAFINAL = '20170110';
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL;
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL);
END;