DECLARE @DATA_INICIAL DATE;
DECLARE @DATA_FINAL DATE;
DECLARE @NUMNOTAS INT;

SET @DATA_INICIAL = '2017-01-01';
SET @DATA_FINAL = '2017-01-10';

WHILE @DATA_INICIAL <= @DATA_FINAL

BEGIN

    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_INICIAL
	PRINT CONVERT(VARCHAR(10), @DATA_INICIAL) + CONVERT(VARCHAR(10), @NUMNOTAS)
	SELECT @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL)
END;
