DECLARE @CODIGO VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_PRODUTOS INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @I INT;

SET @MES = 1;
SET @ANO = 2015;
SELECT @NUMERO_PRODUTOS = COUNT(*) FROM [TABELA DE PRODUTOS];
SET @I = 1;

WHILE @I <= @NUMERO_PRODUTOS
     BEGIN
        SELECT @CODIGO = X.[CODIGO DO PRODUTO], @NOME = X.[NOME DO PRODUTO]
        FROM ( SELECT Row_Number() Over (Order By [CODIGO DO PRODUTO]) as RowNum, * FROM [TABELA DE PRODUTOS]) X
        WHERE X.RowNum = @I;

		SELECT @TOTAL_VENDAS = SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO])
        FROM [NOTAS FISCAIS]
        INNER JOIN [ITENS NOTAS FISCAIS]
        ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
        WHERE [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = @CODIGO
        AND YEAR([NOTAS FISCAIS].DATA) = @ANO AND MONTH([NOTAS FISCAIS].DATA) = @MES;

        PRINT 'Vendas para ' + @CODIGO + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + CONVERT(VARCHAR(4), @ANO) + ' FOI DE ' +  CONVERT(VARCHAR(20), @TOTAL_VENDAS);
        SET @I = @I + 1;
     END;

